version: "2"
run:
  concurrency: 8
output:
  sort-order:
    - linter
    - file
    - severity
linters:
  default: none
  enable: # https://golangci-lint.run/docs/linters
    - govet
    - errcheck # Detects unhandled errors.
    - errorlint # Finds code that can cause problems with the error wrapping scheme introduced in Go 1.13.
    # - sloglint # Ensures consistent code style when using log/slog.
    # - wrapcheck # Checks that errors returned from external packages are wrapped.
    - staticcheck # Enables SA checks: https://staticcheck.dev/docs/checks
    - unused # Checks for unused constants, variables, functions and types.
    - bodyclose # Checks whether HTTP response body is closed successfully.
    - errname # Enforces that sentinel errors are prefixed with the Err and error types are suffixed with the Error.
    - exptostd # Detects functions from golang.org/x/exp/ that can be replaced by std functions.
    - fatcontext # Detects nested contexts in loops and function literals.
    - usestdlibvars # Detects the possibility to use variables/constants from the Go standard library.
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    sloglint:
      attr-only: true
      context: "all"
      no-global: "all"
      key-naming-case: camel
    usestdlibvars:
      http-status-code: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - .*\.gen\.go$
      - .*\.ridl$
      - vendor
      - tools
      - scripts
      - bin
      - .buildkite
      - etc
      - proto/clients
      - tests/mock
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/0xsequence/quotacontrol)
      custom-order: true
      no-lex-order: false
  exclusions:
    generated: lax
    paths:
      - .*\.gen\.go$
      - .*\.ridl$
      - vendor
      - tools
      - scripts
      - bin
      - .buildkite
      - etc
      - proto/clients
      - tests/mock
      - third_party$
      - builtin$
      - examples$