// quota-control v0-26.1.5+3f8a484 c6308c7b6ed880318262a4e07406dc3c5c21a856
// --
// Code generated by webrpc-gen@v0.31.1 with golang generator. DO NOT EDIT.
//
// webrpc-gen -schema=quotacontrol.ridl -target=golang -pkg=proto -server -client -out=./quotacontrol.gen.go
package proto

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/goware/validation"
)

// WebRPC description and code-gen version
func WebRPCVersion() string {
	return "v1"
}

// Schema version of your RIDL schema
func WebRPCSchemaVersion() string {
	return "v0-26.1.5+3f8a484"
}

// Schema hash generated from your RIDL schema
func WebRPCSchemaHash() string {
	return "c6308c7b6ed880318262a4e07406dc3c5c21a856"
}

//
// Client interface
//

type QuotaControlClient interface {
	// Status
	GetProjectStatus(ctx context.Context, projectId uint64) (*ProjectStatus, error)
	// Access Key
	GetAccessKey(ctx context.Context, accessKey string) (*AccessKey, error)
	CreateAccessKey(ctx context.Context, projectId uint64, displayName string, requireOrigin bool, allowedOrigins []string, allowedServices []Service) (*AccessKey, error)
	UpdateAccessKey(ctx context.Context, accessKey string, displayName *string, requireOrigin *bool, allowedOrigins []string, allowedServices []Service) (*AccessKey, error)
	ListAccessKeys(ctx context.Context, projectId uint64, active *bool, service *Service) ([]*AccessKey, error)
	RotateAccessKey(ctx context.Context, accessKey string) (*AccessKey, error)
	DisableAccessKey(ctx context.Context, accessKey string) (bool, error)
	// Default Access Keys
	GetDefaultAccessKey(ctx context.Context, projectID uint64) (*AccessKey, error)
	SetDefaultAccessKey(ctx context.Context, projectID uint64, accessKey string) (bool, error)
	// Quota
	GetProjectQuota(ctx context.Context, projectId uint64, now time.Time) (*AccessQuota, error)
	GetAccessQuota(ctx context.Context, accessKey string, now time.Time) (*AccessQuota, error)
	ClearAccessQuotaCache(ctx context.Context, projectID uint64) (bool, error)
	// Usage
	GetUsage(ctx context.Context, projectID uint64, accessKey *string, service *Service, from *time.Time, to *time.Time) (int64, error)
	ClearUsage(ctx context.Context, projectID uint64, service *Service, now time.Time) (bool, error)
	SyncProjectUsage(ctx context.Context, service Service, now time.Time, usage map[uint64]int64) (map[uint64]bool, error)
	SyncAccessKeyUsage(ctx context.Context, service Service, now time.Time, usage map[string]int64) (map[string]bool, error)
	NotifyEvent(ctx context.Context, projectID uint64, service Service, eventType EventType) (bool, error)
	// User permissions for a projectId
	GetUserPermission(ctx context.Context, projectId uint64, userId string) (UserPermission, *ResourceAccess, error)
	// Deprecated: use GetUsage
	GetAccountUsage(ctx context.Context, projectID uint64, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error)
	// Deprecated: use GetUsage
	GetAccessKeyUsage(ctx context.Context, accessKey string, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error)
	// Deprecated: use GetUsage
	GetAsyncUsage(ctx context.Context, projectID uint64, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error)
	// Deprecated: use SyncProjectUsage
	UpdateProjectUsage(ctx context.Context, service Service, now time.Time, usage map[uint64]*AccessUsage) (map[uint64]bool, error)
	// Deprecated: use SyncAccessKeyUsage
	UpdateKeyUsage(ctx context.Context, service Service, now time.Time, usage map[string]*AccessUsage) (map[string]bool, error)
	// Deprecated: client handles caching directly now, this will be removed in the future
	PrepareUsage(ctx context.Context, projectID uint64, service *Service, cycle *Cycle, now time.Time) (bool, error)
}

//
// Server interface
//

type QuotaControlServer interface {
	// Status
	GetProjectStatus(ctx context.Context, projectId uint64) (*ProjectStatus, error)
	// Access Key
	GetAccessKey(ctx context.Context, accessKey string) (*AccessKey, error)
	CreateAccessKey(ctx context.Context, projectId uint64, displayName string, requireOrigin bool, allowedOrigins []string, allowedServices []Service) (*AccessKey, error)
	UpdateAccessKey(ctx context.Context, accessKey string, displayName *string, requireOrigin *bool, allowedOrigins []string, allowedServices []Service) (*AccessKey, error)
	ListAccessKeys(ctx context.Context, projectId uint64, active *bool, service *Service) ([]*AccessKey, error)
	RotateAccessKey(ctx context.Context, accessKey string) (*AccessKey, error)
	DisableAccessKey(ctx context.Context, accessKey string) (bool, error)
	// Default Access Keys
	GetDefaultAccessKey(ctx context.Context, projectID uint64) (*AccessKey, error)
	SetDefaultAccessKey(ctx context.Context, projectID uint64, accessKey string) (bool, error)
	// Quota
	GetProjectQuota(ctx context.Context, projectId uint64, now time.Time) (*AccessQuota, error)
	GetAccessQuota(ctx context.Context, accessKey string, now time.Time) (*AccessQuota, error)
	ClearAccessQuotaCache(ctx context.Context, projectID uint64) (bool, error)
	// Usage
	GetUsage(ctx context.Context, projectID uint64, accessKey *string, service *Service, from *time.Time, to *time.Time) (int64, error)
	ClearUsage(ctx context.Context, projectID uint64, service *Service, now time.Time) (bool, error)
	SyncProjectUsage(ctx context.Context, service Service, now time.Time, usage map[uint64]int64) (map[uint64]bool, error)
	SyncAccessKeyUsage(ctx context.Context, service Service, now time.Time, usage map[string]int64) (map[string]bool, error)
	NotifyEvent(ctx context.Context, projectID uint64, service Service, eventType EventType) (bool, error)
	// User permissions for a projectId
	GetUserPermission(ctx context.Context, projectId uint64, userId string) (UserPermission, *ResourceAccess, error)
	// Deprecated: use GetUsage
	GetAccountUsage(ctx context.Context, projectID uint64, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error)
	// Deprecated: use GetUsage
	GetAccessKeyUsage(ctx context.Context, accessKey string, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error)
	// Deprecated: use GetUsage
	GetAsyncUsage(ctx context.Context, projectID uint64, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error)
	// Deprecated: use SyncProjectUsage
	UpdateProjectUsage(ctx context.Context, service Service, now time.Time, usage map[uint64]*AccessUsage) (map[uint64]bool, error)
	// Deprecated: use SyncAccessKeyUsage
	UpdateKeyUsage(ctx context.Context, service Service, now time.Time, usage map[string]*AccessUsage) (map[string]bool, error)
	// Deprecated: client handles caching directly now, this will be removed in the future
	PrepareUsage(ctx context.Context, projectID uint64, service *Service, cycle *Cycle, now time.Time) (bool, error)
}

//
// Schema types
//

type Service uint16

const (
	Service_NodeGateway Service = 0
	Service_API         Service = 1
	Service_Indexer     Service = 2
	Service_Relayer     Service = 3
	Service_Metadata    Service = 4
	Service_Marketplace Service = 5
	Service_Builder     Service = 6
	Service_WaaS        Service = 7
	Service_Trails      Service = 8
)

var Service_name = map[uint16]string{
	0: "NodeGateway",
	1: "API",
	2: "Indexer",
	3: "Relayer",
	4: "Metadata",
	5: "Marketplace",
	6: "Builder",
	7: "WaaS",
	8: "Trails",
}

var Service_value = map[string]uint16{
	"NodeGateway": 0,
	"API":         1,
	"Indexer":     2,
	"Relayer":     3,
	"Metadata":    4,
	"Marketplace": 5,
	"Builder":     6,
	"WaaS":        7,
	"Trails":      8,
}

func (x Service) String() string {
	return Service_name[uint16(x)]
}

func (x Service) MarshalText() ([]byte, error) {
	return []byte(Service_name[uint16(x)]), nil
}

func (x *Service) UnmarshalText(b []byte) error {
	*x = Service(Service_value[string(b)])
	return nil
}

func (x *Service) Is(values ...Service) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type EventType uint16

const (
	EventType_FreeWarn EventType = 0
	EventType_FreeMax  EventType = 1
	EventType_OverWarn EventType = 2
	EventType_OverMax  EventType = 3
)

var EventType_name = map[uint16]string{
	0: "FreeWarn",
	1: "FreeMax",
	2: "OverWarn",
	3: "OverMax",
}

var EventType_value = map[string]uint16{
	"FreeWarn": 0,
	"FreeMax":  1,
	"OverWarn": 2,
	"OverMax":  3,
}

func (x EventType) String() string {
	return EventType_name[uint16(x)]
}

func (x EventType) MarshalText() ([]byte, error) {
	return []byte(EventType_name[uint16(x)]), nil
}

func (x *EventType) UnmarshalText(b []byte) error {
	*x = EventType(EventType_value[string(b)])
	return nil
}

func (x *EventType) Is(values ...EventType) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

type UserPermission uint16

const (
	UserPermission_UNAUTHORIZED UserPermission = 0
	UserPermission_READ         UserPermission = 1
	UserPermission_READ_WRITE   UserPermission = 2
	UserPermission_ADMIN        UserPermission = 3
)

var UserPermission_name = map[uint16]string{
	0: "UNAUTHORIZED",
	1: "READ",
	2: "READ_WRITE",
	3: "ADMIN",
}

var UserPermission_value = map[string]uint16{
	"UNAUTHORIZED": 0,
	"READ":         1,
	"READ_WRITE":   2,
	"ADMIN":        3,
}

func (x UserPermission) String() string {
	return UserPermission_name[uint16(x)]
}

func (x UserPermission) MarshalText() ([]byte, error) {
	return []byte(UserPermission_name[uint16(x)]), nil
}

func (x *UserPermission) UnmarshalText(b []byte) error {
	*x = UserPermission(UserPermission_value[string(b)])
	return nil
}

func (x *UserPermission) Is(values ...UserPermission) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}

// LimitSettings is used to define the limits for a project.
type Limit struct {
	// The service-specific limits for the project.
	ServiceLimit map[string]ServiceLimit `json:"serviceLimit"`
	// Deprecated: use base.rateLimit instead
	RateLimit int64 `json:"rateLimit"`
	// Deprecated: use base.freeWarn instead
	FreeWarn int64 `json:"freeWarn"`
	// Deprecated: use base.freeMax instead
	FreeMax int64 `json:"freeMax"`
	// Deprecated: use base.overWarn instead
	OverWarn int64 `json:"overWarn"`
	// Deprecated: use base.overMax instead
	OverMax int64 `json:"overMax"`
}

// ServiceLimit defines the limits for a service.
type ServiceLimit struct {
	// Requests/minute limit for the project.
	RateLimit int64 `json:"rateLimit"`
	// Free usage warning threshold.
	FreeWarn int64 `json:"freeWarn"`
	// Free usage maximum threshold.
	FreeMax int64 `json:"freeMax"`
	// Over usage warning threshold.
	OverWarn int64 `json:"overWarn"`
	// Over usage maximum threshold.
	OverMax int64 `json:"overMax"`
}

type AccessKey struct {
	ProjectID       uint64             `json:"projectId" db:"project_id"`
	ChainIDs        []uint64           `json:"chainIds" db:"chain_ids"`
	DisplayName     string             `json:"displayName" db:"display_name"`
	AccessKey       string             `json:"accessKey" db:"access_key"`
	Active          bool               `json:"active" db:"active"`
	Default         bool               `json:"default" db:"is_default"`
	RequireOrigin   bool               `json:"requireOrigin" db:"require_origin"`
	AllowedOrigins  validation.Origins `json:"allowedOrigins" db:"allowed_origins"`
	AllowedServices []Service          `json:"allowedServices" db:"allowed_services"`
	CreatedAt       *time.Time         `json:"createdAt,omitempty" db:"created_at,omitempty"`
}

// Deprecated: use int64 instead
type AccessUsage struct {
	ValidCompute   int64 `json:"validCompute" db:"valid_compute"`
	OverCompute    int64 `json:"overCompute" db:"over_compute"`
	LimitedCompute int64 `json:"limitedCompute" db:"limited_compute"`
}

type Cycle struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type AccessQuota struct {
	Cycle     *Cycle     `json:"cycle"`
	Limit     *Limit     `json:"limit"`
	AccessKey *AccessKey `json:"accessKey"`
}

type ProjectStatus struct {
	ProjectID        uint64           `json:"projectId"`
	Limit            *Limit           `json:"limit"`
	UsageCounter     map[string]int64 `json:"usageCounter"`
	RateLimitCounter map[string]int64 `json:"rateLimitCounter"`
}

type Subscription struct {
	Tier string `json:"tier"`
}

type Minter struct {
	Contracts []string `json:"contracts"`
}

type ResourceAccess struct {
	ProjectID    uint64        `json:"projectId"`
	Subscription *Subscription `json:"subscription"`
	Minter       *Minter       `json:"minter"`
}

//
// Client
//

const QuotaControlPathPrefix = "/rpc/QuotaControl/"

type quotaControlClient struct {
	client HTTPClient
	urls   [24]string
}

func NewQuotaControlClient(addr string, client HTTPClient) QuotaControlClient {
	prefix := urlBase(addr) + QuotaControlPathPrefix
	urls := [24]string{
		prefix + "GetProjectStatus",
		prefix + "GetAccessKey",
		prefix + "CreateAccessKey",
		prefix + "UpdateAccessKey",
		prefix + "ListAccessKeys",
		prefix + "RotateAccessKey",
		prefix + "DisableAccessKey",
		prefix + "GetDefaultAccessKey",
		prefix + "SetDefaultAccessKey",
		prefix + "GetProjectQuota",
		prefix + "GetAccessQuota",
		prefix + "ClearAccessQuotaCache",
		prefix + "GetUsage",
		prefix + "ClearUsage",
		prefix + "SyncProjectUsage",
		prefix + "SyncAccessKeyUsage",
		prefix + "NotifyEvent",
		prefix + "GetUserPermission",
		prefix + "GetAccountUsage",
		prefix + "GetAccessKeyUsage",
		prefix + "GetAsyncUsage",
		prefix + "UpdateProjectUsage",
		prefix + "UpdateKeyUsage",
		prefix + "PrepareUsage",
	}
	return &quotaControlClient{
		client: client,
		urls:   urls,
	}
}

func (c *quotaControlClient) GetProjectStatus(ctx context.Context, projectId uint64) (*ProjectStatus, error) {
	in := struct {
		Arg0 uint64 `json:"projectId"`
	}{projectId}
	out := struct {
		Ret0 *ProjectStatus `json:"projectStatus"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[0], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetAccessKey(ctx context.Context, accessKey string) (*AccessKey, error) {
	in := struct {
		Arg0 string `json:"accessKey"`
	}{accessKey}
	out := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[1], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) CreateAccessKey(ctx context.Context, projectId uint64, displayName string, requireOrigin bool, allowedOrigins []string, allowedServices []Service) (*AccessKey, error) {
	in := struct {
		Arg0 uint64    `json:"projectId"`
		Arg1 string    `json:"displayName"`
		Arg2 bool      `json:"requireOrigin"`
		Arg3 []string  `json:"allowedOrigins"`
		Arg4 []Service `json:"allowedServices"`
	}{projectId, displayName, requireOrigin, allowedOrigins, allowedServices}
	out := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[2], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) UpdateAccessKey(ctx context.Context, accessKey string, displayName *string, requireOrigin *bool, allowedOrigins []string, allowedServices []Service) (*AccessKey, error) {
	in := struct {
		Arg0 string    `json:"accessKey"`
		Arg1 *string   `json:"displayName"`
		Arg2 *bool     `json:"requireOrigin"`
		Arg3 []string  `json:"allowedOrigins"`
		Arg4 []Service `json:"allowedServices"`
	}{accessKey, displayName, requireOrigin, allowedOrigins, allowedServices}
	out := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[3], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) ListAccessKeys(ctx context.Context, projectId uint64, active *bool, service *Service) ([]*AccessKey, error) {
	in := struct {
		Arg0 uint64   `json:"projectId"`
		Arg1 *bool    `json:"active"`
		Arg2 *Service `json:"service"`
	}{projectId, active, service}
	out := struct {
		Ret0 []*AccessKey `json:"accessKeys"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[4], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) RotateAccessKey(ctx context.Context, accessKey string) (*AccessKey, error) {
	in := struct {
		Arg0 string `json:"accessKey"`
	}{accessKey}
	out := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[5], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) DisableAccessKey(ctx context.Context, accessKey string) (bool, error) {
	in := struct {
		Arg0 string `json:"accessKey"`
	}{accessKey}
	out := struct {
		Ret0 bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[6], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetDefaultAccessKey(ctx context.Context, projectID uint64) (*AccessKey, error) {
	in := struct {
		Arg0 uint64 `json:"projectID"`
	}{projectID}
	out := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[7], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) SetDefaultAccessKey(ctx context.Context, projectID uint64, accessKey string) (bool, error) {
	in := struct {
		Arg0 uint64 `json:"projectID"`
		Arg1 string `json:"accessKey"`
	}{projectID, accessKey}
	out := struct {
		Ret0 bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[8], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetProjectQuota(ctx context.Context, projectId uint64, now time.Time) (*AccessQuota, error) {
	in := struct {
		Arg0 uint64    `json:"projectId"`
		Arg1 time.Time `json:"now"`
	}{projectId, now}
	out := struct {
		Ret0 *AccessQuota `json:"accessQuota"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[9], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetAccessQuota(ctx context.Context, accessKey string, now time.Time) (*AccessQuota, error) {
	in := struct {
		Arg0 string    `json:"accessKey"`
		Arg1 time.Time `json:"now"`
	}{accessKey, now}
	out := struct {
		Ret0 *AccessQuota `json:"accessQuota"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[10], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) ClearAccessQuotaCache(ctx context.Context, projectID uint64) (bool, error) {
	in := struct {
		Arg0 uint64 `json:"projectID"`
	}{projectID}
	out := struct {
		Ret0 bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[11], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetUsage(ctx context.Context, projectID uint64, accessKey *string, service *Service, from *time.Time, to *time.Time) (int64, error) {
	in := struct {
		Arg0 uint64     `json:"projectID"`
		Arg1 *string    `json:"accessKey"`
		Arg2 *Service   `json:"service"`
		Arg3 *time.Time `json:"from"`
		Arg4 *time.Time `json:"to"`
	}{projectID, accessKey, service, from, to}
	out := struct {
		Ret0 int64 `json:"usage"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[12], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) ClearUsage(ctx context.Context, projectID uint64, service *Service, now time.Time) (bool, error) {
	in := struct {
		Arg0 uint64    `json:"projectID"`
		Arg1 *Service  `json:"service"`
		Arg2 time.Time `json:"now"`
	}{projectID, service, now}
	out := struct {
		Ret0 bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[13], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) SyncProjectUsage(ctx context.Context, service Service, now time.Time, usage map[uint64]int64) (map[uint64]bool, error) {
	in := struct {
		Arg0 Service          `json:"service"`
		Arg1 time.Time        `json:"now"`
		Arg2 map[uint64]int64 `json:"usage"`
	}{service, now, usage}
	out := struct {
		Ret0 map[uint64]bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[14], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) SyncAccessKeyUsage(ctx context.Context, service Service, now time.Time, usage map[string]int64) (map[string]bool, error) {
	in := struct {
		Arg0 Service          `json:"service"`
		Arg1 time.Time        `json:"now"`
		Arg2 map[string]int64 `json:"usage"`
	}{service, now, usage}
	out := struct {
		Ret0 map[string]bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[15], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) NotifyEvent(ctx context.Context, projectID uint64, service Service, eventType EventType) (bool, error) {
	in := struct {
		Arg0 uint64    `json:"projectID"`
		Arg1 Service   `json:"service"`
		Arg2 EventType `json:"eventType"`
	}{projectID, service, eventType}
	out := struct {
		Ret0 bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[16], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetUserPermission(ctx context.Context, projectId uint64, userId string) (UserPermission, *ResourceAccess, error) {
	in := struct {
		Arg0 uint64 `json:"projectId"`
		Arg1 string `json:"userId"`
	}{projectId, userId}
	out := struct {
		Ret0 UserPermission  `json:"permission"`
		Ret1 *ResourceAccess `json:"resourceAccess"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[17], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, out.Ret1, err
}

func (c *quotaControlClient) GetAccountUsage(ctx context.Context, projectID uint64, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error) {
	in := struct {
		Arg0 uint64     `json:"projectID"`
		Arg1 *Service   `json:"service"`
		Arg2 *time.Time `json:"from"`
		Arg3 *time.Time `json:"to"`
	}{projectID, service, from, to}
	out := struct {
		Ret0 *AccessUsage `json:"usage"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[18], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetAccessKeyUsage(ctx context.Context, accessKey string, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error) {
	in := struct {
		Arg0 string     `json:"accessKey"`
		Arg1 *Service   `json:"service"`
		Arg2 *time.Time `json:"from"`
		Arg3 *time.Time `json:"to"`
	}{accessKey, service, from, to}
	out := struct {
		Ret0 *AccessUsage `json:"usage"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[19], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) GetAsyncUsage(ctx context.Context, projectID uint64, service *Service, from *time.Time, to *time.Time) (*AccessUsage, error) {
	in := struct {
		Arg0 uint64     `json:"projectID"`
		Arg1 *Service   `json:"service"`
		Arg2 *time.Time `json:"from"`
		Arg3 *time.Time `json:"to"`
	}{projectID, service, from, to}
	out := struct {
		Ret0 *AccessUsage `json:"usage"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[20], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) UpdateProjectUsage(ctx context.Context, service Service, now time.Time, usage map[uint64]*AccessUsage) (map[uint64]bool, error) {
	in := struct {
		Arg0 Service                 `json:"service"`
		Arg1 time.Time               `json:"now"`
		Arg2 map[uint64]*AccessUsage `json:"usage"`
	}{service, now, usage}
	out := struct {
		Ret0 map[uint64]bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[21], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) UpdateKeyUsage(ctx context.Context, service Service, now time.Time, usage map[string]*AccessUsage) (map[string]bool, error) {
	in := struct {
		Arg0 Service                 `json:"service"`
		Arg1 time.Time               `json:"now"`
		Arg2 map[string]*AccessUsage `json:"usage"`
	}{service, now, usage}
	out := struct {
		Ret0 map[string]bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[22], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *quotaControlClient) PrepareUsage(ctx context.Context, projectID uint64, service *Service, cycle *Cycle, now time.Time) (bool, error) {
	in := struct {
		Arg0 uint64    `json:"projectID"`
		Arg1 *Service  `json:"service"`
		Arg2 *Cycle    `json:"cycle"`
		Arg3 time.Time `json:"now"`
	}{projectID, service, cycle, now}
	out := struct {
		Ret0 bool `json:"ok"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[23], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

//
// Server
//

type WebRPCServer interface {
	http.Handler
}

type quotaControlService struct {
	QuotaControlServer
	OnError   func(r *http.Request, rpcErr *WebRPCError)
	OnRequest func(w http.ResponseWriter, r *http.Request) error
}

func NewQuotaControlServer(svc QuotaControlServer) *quotaControlService {
	return &quotaControlService{
		QuotaControlServer: svc,
	}
}

func (s *quotaControlService) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer func() {
		// In case of a panic, serve a HTTP 500 error and then panic.
		if rr := recover(); rr != nil {
			s.sendErrorJSON(w, r, ErrWebrpcServerPanic.WithCausef("%v", rr))
			panic(rr)
		}
	}()

	w.Header().Set(WebrpcHeader, WebrpcHeaderValue)

	ctx := r.Context()
	ctx = context.WithValue(ctx, HTTPResponseWriterCtxKey, w)
	ctx = context.WithValue(ctx, HTTPRequestCtxKey, r)
	ctx = context.WithValue(ctx, ServiceNameCtxKey, "QuotaControl")

	r = r.WithContext(ctx)

	var handler func(ctx context.Context, w http.ResponseWriter, r *http.Request)
	switch r.URL.Path {
	case "/rpc/QuotaControl/GetProjectStatus":
		handler = s.serveGetProjectStatusJSON
	case "/rpc/QuotaControl/GetAccessKey":
		handler = s.serveGetAccessKeyJSON
	case "/rpc/QuotaControl/CreateAccessKey":
		handler = s.serveCreateAccessKeyJSON
	case "/rpc/QuotaControl/UpdateAccessKey":
		handler = s.serveUpdateAccessKeyJSON
	case "/rpc/QuotaControl/ListAccessKeys":
		handler = s.serveListAccessKeysJSON
	case "/rpc/QuotaControl/RotateAccessKey":
		handler = s.serveRotateAccessKeyJSON
	case "/rpc/QuotaControl/DisableAccessKey":
		handler = s.serveDisableAccessKeyJSON
	case "/rpc/QuotaControl/GetDefaultAccessKey":
		handler = s.serveGetDefaultAccessKeyJSON
	case "/rpc/QuotaControl/SetDefaultAccessKey":
		handler = s.serveSetDefaultAccessKeyJSON
	case "/rpc/QuotaControl/GetProjectQuota":
		handler = s.serveGetProjectQuotaJSON
	case "/rpc/QuotaControl/GetAccessQuota":
		handler = s.serveGetAccessQuotaJSON
	case "/rpc/QuotaControl/ClearAccessQuotaCache":
		handler = s.serveClearAccessQuotaCacheJSON
	case "/rpc/QuotaControl/GetUsage":
		handler = s.serveGetUsageJSON
	case "/rpc/QuotaControl/ClearUsage":
		handler = s.serveClearUsageJSON
	case "/rpc/QuotaControl/SyncProjectUsage":
		handler = s.serveSyncProjectUsageJSON
	case "/rpc/QuotaControl/SyncAccessKeyUsage":
		handler = s.serveSyncAccessKeyUsageJSON
	case "/rpc/QuotaControl/NotifyEvent":
		handler = s.serveNotifyEventJSON
	case "/rpc/QuotaControl/GetUserPermission":
		handler = s.serveGetUserPermissionJSON
	case "/rpc/QuotaControl/GetAccountUsage":
		handler = s.serveGetAccountUsageJSON
	case "/rpc/QuotaControl/GetAccessKeyUsage":
		handler = s.serveGetAccessKeyUsageJSON
	case "/rpc/QuotaControl/GetAsyncUsage":
		handler = s.serveGetAsyncUsageJSON
	case "/rpc/QuotaControl/UpdateProjectUsage":
		handler = s.serveUpdateProjectUsageJSON
	case "/rpc/QuotaControl/UpdateKeyUsage":
		handler = s.serveUpdateKeyUsageJSON
	case "/rpc/QuotaControl/PrepareUsage":
		handler = s.servePrepareUsageJSON
	default:
		err := ErrWebrpcBadRoute.WithCausef("no webrpc method defined for path %v", r.URL.Path)
		s.sendErrorJSON(w, r, err)
		return
	}

	if r.Method != "POST" {
		w.Header().Add("Allow", "POST") // RFC 9110.
		err := ErrWebrpcBadMethod.WithCausef("unsupported HTTP method %v (only POST is allowed)", r.Method)
		s.sendErrorJSON(w, r, err)
		return
	}

	contentType := r.Header.Get("Content-Type")
	if i := strings.Index(contentType, ";"); i >= 0 {
		contentType = contentType[:i]
	}
	contentType = strings.TrimSpace(strings.ToLower(contentType))

	switch contentType {
	case "application/json":
		if s.OnRequest != nil {
			if err := s.OnRequest(w, r); err != nil {
				rpcErr, ok := err.(WebRPCError)
				if !ok {
					rpcErr = ErrWebrpcEndpoint.WithCause(err)
				}
				s.sendErrorJSON(w, r, rpcErr)
				return
			}
		}

		handler(ctx, w, r)
	default:
		err := ErrWebrpcBadRequest.WithCausef("unsupported Content-Type %q (only application/json is allowed)", r.Header.Get("Content-Type"))
		s.sendErrorJSON(w, r, err)
	}
}

func (s *quotaControlService) serveGetProjectStatusJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetProjectStatus")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64 `json:"projectId"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetProjectStatus(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *ProjectStatus `json:"projectStatus"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 string `json:"accessKey"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetAccessKey(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveCreateAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "CreateAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64    `json:"projectId"`
		Arg1 string    `json:"displayName"`
		Arg2 bool      `json:"requireOrigin"`
		Arg3 []string  `json:"allowedOrigins"`
		Arg4 []Service `json:"allowedServices"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.CreateAccessKey(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3, reqPayload.Arg4)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveUpdateAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "UpdateAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 string    `json:"accessKey"`
		Arg1 *string   `json:"displayName"`
		Arg2 *bool     `json:"requireOrigin"`
		Arg3 []string  `json:"allowedOrigins"`
		Arg4 []Service `json:"allowedServices"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.UpdateAccessKey(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3, reqPayload.Arg4)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveListAccessKeysJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "ListAccessKeys")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64   `json:"projectId"`
		Arg1 *bool    `json:"active"`
		Arg2 *Service `json:"service"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.ListAccessKeys(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 []*AccessKey `json:"accessKeys"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveRotateAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "RotateAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 string `json:"accessKey"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.RotateAccessKey(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveDisableAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "DisableAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 string `json:"accessKey"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.DisableAccessKey(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetDefaultAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetDefaultAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64 `json:"projectID"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetDefaultAccessKey(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessKey `json:"accessKey"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveSetDefaultAccessKeyJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "SetDefaultAccessKey")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64 `json:"projectID"`
		Arg1 string `json:"accessKey"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.SetDefaultAccessKey(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetProjectQuotaJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetProjectQuota")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64    `json:"projectId"`
		Arg1 time.Time `json:"now"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetProjectQuota(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessQuota `json:"accessQuota"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetAccessQuotaJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetAccessQuota")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 string    `json:"accessKey"`
		Arg1 time.Time `json:"now"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetAccessQuota(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessQuota `json:"accessQuota"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveClearAccessQuotaCacheJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "ClearAccessQuotaCache")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64 `json:"projectID"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.ClearAccessQuotaCache(ctx, reqPayload.Arg0)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64     `json:"projectID"`
		Arg1 *string    `json:"accessKey"`
		Arg2 *Service   `json:"service"`
		Arg3 *time.Time `json:"from"`
		Arg4 *time.Time `json:"to"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3, reqPayload.Arg4)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 int64 `json:"usage"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveClearUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "ClearUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64    `json:"projectID"`
		Arg1 *Service  `json:"service"`
		Arg2 time.Time `json:"now"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.ClearUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveSyncProjectUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "SyncProjectUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 Service          `json:"service"`
		Arg1 time.Time        `json:"now"`
		Arg2 map[uint64]int64 `json:"usage"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.SyncProjectUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 map[uint64]bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveSyncAccessKeyUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "SyncAccessKeyUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 Service          `json:"service"`
		Arg1 time.Time        `json:"now"`
		Arg2 map[string]int64 `json:"usage"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.SyncAccessKeyUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 map[string]bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveNotifyEventJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "NotifyEvent")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64    `json:"projectID"`
		Arg1 Service   `json:"service"`
		Arg2 EventType `json:"eventType"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.NotifyEvent(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetUserPermissionJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetUserPermission")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64 `json:"projectId"`
		Arg1 string `json:"userId"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, ret1, err := s.QuotaControlServer.GetUserPermission(ctx, reqPayload.Arg0, reqPayload.Arg1)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 UserPermission  `json:"permission"`
		Ret1 *ResourceAccess `json:"resourceAccess"`
	}{ret0, ret1}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetAccountUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetAccountUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64     `json:"projectID"`
		Arg1 *Service   `json:"service"`
		Arg2 *time.Time `json:"from"`
		Arg3 *time.Time `json:"to"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetAccountUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessUsage `json:"usage"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetAccessKeyUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetAccessKeyUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 string     `json:"accessKey"`
		Arg1 *Service   `json:"service"`
		Arg2 *time.Time `json:"from"`
		Arg3 *time.Time `json:"to"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetAccessKeyUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessUsage `json:"usage"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveGetAsyncUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "GetAsyncUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64     `json:"projectID"`
		Arg1 *Service   `json:"service"`
		Arg2 *time.Time `json:"from"`
		Arg3 *time.Time `json:"to"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.GetAsyncUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 *AccessUsage `json:"usage"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveUpdateProjectUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "UpdateProjectUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 Service                 `json:"service"`
		Arg1 time.Time               `json:"now"`
		Arg2 map[uint64]*AccessUsage `json:"usage"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.UpdateProjectUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 map[uint64]bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) serveUpdateKeyUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "UpdateKeyUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 Service                 `json:"service"`
		Arg1 time.Time               `json:"now"`
		Arg2 map[string]*AccessUsage `json:"usage"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.UpdateKeyUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 map[string]bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) servePrepareUsageJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "PrepareUsage")

	reqBody, err := io.ReadAll(r.Body)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
		return
	}
	defer r.Body.Close()

	reqPayload := struct {
		Arg0 uint64    `json:"projectID"`
		Arg1 *Service  `json:"service"`
		Arg2 *Cycle    `json:"cycle"`
		Arg3 time.Time `json:"now"`
	}{}
	if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
		return
	}

	// Call service method implementation.
	ret0, err := s.QuotaControlServer.PrepareUsage(ctx, reqPayload.Arg0, reqPayload.Arg1, reqPayload.Arg2, reqPayload.Arg3)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	respPayload := struct {
		Ret0 bool `json:"ok"`
	}{ret0}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *quotaControlService) sendErrorJSON(w http.ResponseWriter, r *http.Request, rpcErr WebRPCError) {
	if s.OnError != nil {
		s.OnError(r, &rpcErr)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

func RespondWithError(w http.ResponseWriter, err error) {
	rpcErr, ok := err.(WebRPCError)
	if !ok {
		rpcErr = ErrWebrpcEndpoint.WithCause(err)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

type method struct {
	name        string
	service     string
	annotations map[string]string
}

func (m *method) Name() string                   { return m.name }
func (m *method) Service() string                { return m.service }
func (m *method) Annotations() map[string]string { return m.annotations }

var methods = map[string]*method{
	"/rpc/QuotaControl/GetProjectStatus": {
		name:        "GetProjectStatus",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetAccessKey": {
		name:        "GetAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/CreateAccessKey": {
		name:        "CreateAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/UpdateAccessKey": {
		name:        "UpdateAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/ListAccessKeys": {
		name:        "ListAccessKeys",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/RotateAccessKey": {
		name:        "RotateAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/DisableAccessKey": {
		name:        "DisableAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetDefaultAccessKey": {
		name:        "GetDefaultAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/SetDefaultAccessKey": {
		name:        "SetDefaultAccessKey",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetProjectQuota": {
		name:        "GetProjectQuota",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetAccessQuota": {
		name:        "GetAccessQuota",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/ClearAccessQuotaCache": {
		name:        "ClearAccessQuotaCache",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetUsage": {
		name:        "GetUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/ClearUsage": {
		name:        "ClearUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/SyncProjectUsage": {
		name:        "SyncProjectUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/SyncAccessKeyUsage": {
		name:        "SyncAccessKeyUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/NotifyEvent": {
		name:        "NotifyEvent",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetUserPermission": {
		name:        "GetUserPermission",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetAccountUsage": {
		name:        "GetAccountUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetAccessKeyUsage": {
		name:        "GetAccessKeyUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/GetAsyncUsage": {
		name:        "GetAsyncUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/UpdateProjectUsage": {
		name:        "UpdateProjectUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/UpdateKeyUsage": {
		name:        "UpdateKeyUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
	"/rpc/QuotaControl/PrepareUsage": {
		name:        "PrepareUsage",
		service:     "QuotaControl",
		annotations: map[string]string{},
	},
}

func MethodCtx(ctx context.Context) (*method, bool) {
	req := RequestFromContext(ctx)
	if req == nil {
		return nil, false
	}

	m, ok := methods[req.URL.Path]
	return m, ok
}

func WebrpcMethods() map[string]*method {
	return methods
}

var WebRPCServices = map[string][]string{
	"QuotaControl": {
		"GetProjectStatus",
		"GetAccessKey",
		"CreateAccessKey",
		"UpdateAccessKey",
		"ListAccessKeys",
		"RotateAccessKey",
		"DisableAccessKey",
		"GetDefaultAccessKey",
		"SetDefaultAccessKey",
		"GetProjectQuota",
		"GetAccessQuota",
		"ClearAccessQuotaCache",
		"GetUsage",
		"ClearUsage",
		"SyncProjectUsage",
		"SyncAccessKeyUsage",
		"NotifyEvent",
		"GetUserPermission",
		"GetAccountUsage",
		"GetAccessKeyUsage",
		"GetAsyncUsage",
		"UpdateProjectUsage",
		"UpdateKeyUsage",
		"PrepareUsage",
	},
}

//
// Client helpers
//

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set(WebrpcHeader, WebrpcHeaderValue)
	if headers, ok := HTTPRequestHeaders(ctx); ok {
		for k := range headers {
			for _, v := range headers[k] {
				req.Header.Add(k, v)
			}
		}
	}
	return req, nil
}

// doHTTPRequest is common code to make a request to the remote service.
func doHTTPRequest(ctx context.Context, client HTTPClient, url string, in, out interface{}) (*http.Response, error) {
	reqBody, err := json.Marshal(in)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("failed to marshal JSON body: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("aborted because context was done: %w", err)
	}

	req, err := newRequest(ctx, url, bytes.NewBuffer(reqBody), "application/json")
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("could not build request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCause(err)
	}

	if resp.StatusCode != 200 {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read server error response body: %w", err)
		}

		var rpcErr WebRPCError
		if err := json.Unmarshal(respBody, &rpcErr); err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal server error: %w", err)
		}
		if rpcErr.Cause != "" {
			rpcErr.cause = errors.New(rpcErr.Cause)
		}
		return nil, rpcErr
	}

	if out != nil {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read response body: %w", err)
		}

		err = json.Unmarshal(respBody, &out)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal JSON response body: %w", err)
		}
	}

	return resp, nil
}

func WithHTTPRequestHeaders(ctx context.Context, h http.Header) (context.Context, error) {
	if _, ok := h["Accept"]; ok {
		return nil, errors.New("provided header cannot set Accept")
	}
	if _, ok := h["Content-Type"]; ok {
		return nil, errors.New("provided header cannot set Content-Type")
	}

	copied := make(http.Header, len(h))
	for k, vv := range h {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}

	return context.WithValue(ctx, HTTPClientRequestHeadersCtxKey, copied), nil
}

func HTTPRequestHeaders(ctx context.Context) (http.Header, bool) {
	h, ok := ctx.Value(HTTPClientRequestHeadersCtxKey).(http.Header)
	return h, ok
}

//
// Webrpc helpers
//

type contextKey struct {
	name string
}

func (k *contextKey) String() string {
	return "webrpc context value " + k.name
}

var (
	HTTPClientRequestHeadersCtxKey = &contextKey{"HTTPClientRequestHeaders"}
)

var (
	HTTPResponseWriterCtxKey = &contextKey{"HTTPResponseWriter"}
	MethodNameCtxKey         = &contextKey{"MethodName"}
	HTTPRequestCtxKey        = &contextKey{"HTTPRequest"}
	ServiceNameCtxKey        = &contextKey{"ServiceName"}
)

func ServiceNameFromContext(ctx context.Context) string {
	service, _ := ctx.Value(ServiceNameCtxKey).(string)
	return service
}

func MethodNameFromContext(ctx context.Context) string {
	method, _ := ctx.Value(MethodNameCtxKey).(string)
	return method
}

func RequestFromContext(ctx context.Context) *http.Request {
	r, _ := ctx.Value(HTTPRequestCtxKey).(*http.Request)
	return r
}

// PtrTo is a useful helper when constructing values for optional fields.
func PtrTo[T any](v T) *T { return &v }

func ResponseWriterFromContext(ctx context.Context) http.ResponseWriter {
	w, _ := ctx.Value(HTTPResponseWriterCtxKey).(http.ResponseWriter)
	return w
}

//
// Errors
//

type WebRPCError struct {
	Name       string `json:"error"`
	Code       int    `json:"code"`
	Message    string `json:"msg"`
	Cause      string `json:"cause,omitempty"`
	HTTPStatus int    `json:"status"`
	cause      error
}

var _ error = WebRPCError{}

func (e WebRPCError) Error() string {
	if e.cause != nil {
		return fmt.Sprintf("%s %d: %s: %v", e.Name, e.Code, e.Message, e.cause)
	}
	return fmt.Sprintf("%s %d: %s", e.Name, e.Code, e.Message)
}

func (e WebRPCError) Is(target error) bool {
	if target == nil {
		return false
	}
	if rpcErr, ok := target.(WebRPCError); ok {
		return rpcErr.Code == e.Code
	}
	return errors.Is(e.cause, target)
}

func (e WebRPCError) Unwrap() error {
	return e.cause
}

func (e WebRPCError) WithCause(cause error) WebRPCError {
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

func (e WebRPCError) WithCausef(format string, args ...interface{}) WebRPCError {
	cause := fmt.Errorf(format, args...)
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

// Deprecated: Use .WithCause() method on WebRPCError.
func ErrorWithCause(rpcErr WebRPCError, cause error) WebRPCError {
	return rpcErr.WithCause(cause)
}

// Webrpc errors
var (
	ErrWebrpcEndpoint       = WebRPCError{Code: 0, Name: "WebrpcEndpoint", Message: "endpoint error", HTTPStatus: 400}
	ErrWebrpcRequestFailed  = WebRPCError{Code: -1, Name: "WebrpcRequestFailed", Message: "request failed", HTTPStatus: 400}
	ErrWebrpcBadRoute       = WebRPCError{Code: -2, Name: "WebrpcBadRoute", Message: "bad route", HTTPStatus: 404}
	ErrWebrpcBadMethod      = WebRPCError{Code: -3, Name: "WebrpcBadMethod", Message: "bad method", HTTPStatus: 405}
	ErrWebrpcBadRequest     = WebRPCError{Code: -4, Name: "WebrpcBadRequest", Message: "bad request", HTTPStatus: 400}
	ErrWebrpcBadResponse    = WebRPCError{Code: -5, Name: "WebrpcBadResponse", Message: "bad response", HTTPStatus: 500}
	ErrWebrpcServerPanic    = WebRPCError{Code: -6, Name: "WebrpcServerPanic", Message: "server panic", HTTPStatus: 500}
	ErrWebrpcInternalError  = WebRPCError{Code: -7, Name: "WebrpcInternalError", Message: "internal error", HTTPStatus: 500}
	ErrWebrpcClientAborted  = WebRPCError{Code: -8, Name: "WebrpcClientAborted", Message: "request aborted by client", HTTPStatus: 400}
	ErrWebrpcStreamLost     = WebRPCError{Code: -9, Name: "WebrpcStreamLost", Message: "stream lost", HTTPStatus: 400}
	ErrWebrpcStreamFinished = WebRPCError{Code: -10, Name: "WebrpcStreamFinished", Message: "stream finished", HTTPStatus: 200}
)

// Schema errors
var (
	ErrUnauthorized            = WebRPCError{Code: 1000, Name: "Unauthorized", Message: "Unauthorized access", HTTPStatus: 401}
	ErrPermissionDenied        = WebRPCError{Code: 1001, Name: "PermissionDenied", Message: "Permission denied", HTTPStatus: 403}
	ErrSessionExpired          = WebRPCError{Code: 1002, Name: "SessionExpired", Message: "Session expired", HTTPStatus: 403}
	ErrMethodNotFound          = WebRPCError{Code: 1003, Name: "MethodNotFound", Message: "Method not found", HTTPStatus: 404}
	ErrRequestConflict         = WebRPCError{Code: 1004, Name: "RequestConflict", Message: "Conflict with target resource", HTTPStatus: 409}
	ErrAborted                 = WebRPCError{Code: 1005, Name: "Aborted", Message: "Request aborted", HTTPStatus: 400}
	ErrGeoblocked              = WebRPCError{Code: 1006, Name: "Geoblocked", Message: "Geoblocked region", HTTPStatus: 451}
	ErrRateLimited             = WebRPCError{Code: 1007, Name: "RateLimited", Message: "Rate limit exceeded. Configure an Access Key to increase your limits: https://dashboard.trails.build or https://sequence.build", HTTPStatus: 429}
	ErrProjectNotFound         = WebRPCError{Code: 1008, Name: "ProjectNotFound", Message: "Project not found", HTTPStatus: 401}
	ErrSecretKeyCorsDisallowed = WebRPCError{Code: 1009, Name: "SecretKeyCorsDisallowed", Message: "CORS disallowed. Admin API Secret Key can't be used from a web app.", HTTPStatus: 403}
	ErrInvalidScope            = WebRPCError{Code: 1010, Name: "InvalidScope", Message: "Scope not allowed", HTTPStatus: 403}
	ErrAccessKeyNotFound       = WebRPCError{Code: 1101, Name: "AccessKeyNotFound", Message: "Access key not found", HTTPStatus: 401}
	ErrAccessKeyMismatch       = WebRPCError{Code: 1102, Name: "AccessKeyMismatch", Message: "Access key mismatch", HTTPStatus: 403}
	ErrInvalidOrigin           = WebRPCError{Code: 1103, Name: "InvalidOrigin", Message: "Invalid origin for Access Key. Check your settings at https://dashboard.trails.build or https://sequence.build", HTTPStatus: 403}
	ErrInvalidService          = WebRPCError{Code: 1104, Name: "InvalidService", Message: "Service not enabled for Access key. Check your settings at https://dashboard.trails.build or https://sequence.build", HTTPStatus: 403}
	ErrUnauthorizedUser        = WebRPCError{Code: 1105, Name: "UnauthorizedUser", Message: "Unauthorized user", HTTPStatus: 403}
	ErrInvalidChain            = WebRPCError{Code: 1106, Name: "InvalidChain", Message: "Network not enabled for Access key. Check your settings at https://dashboard.trails.build or https://sequence.build", HTTPStatus: 403}
	ErrQuotaExceeded           = WebRPCError{Code: 1200, Name: "QuotaExceeded", Message: "Project quota exceeded. Upgrade your project to increase your limits: https://dashboard.trails.build or https://sequence.build", HTTPStatus: 423}
	ErrQuotaRateLimit          = WebRPCError{Code: 1201, Name: "QuotaRateLimit", Message: "Project rate limit exceeded. Upgrade your project to increase your limits: https://dashboard.trails.build or https://sequence.build", HTTPStatus: 429}
	ErrNoDefaultKey            = WebRPCError{Code: 1300, Name: "NoDefaultKey", Message: "No default access key found", HTTPStatus: 403}
	ErrMaxAccessKeys           = WebRPCError{Code: 1301, Name: "MaxAccessKeys", Message: "Access keys limit reached", HTTPStatus: 403}
	ErrAtLeastOneKey           = WebRPCError{Code: 1302, Name: "AtLeastOneKey", Message: "You need at least one Access Key", HTTPStatus: 403}
	ErrTimeout                 = WebRPCError{Code: 1900, Name: "Timeout", Message: "Request timed out", HTTPStatus: 408}
)

const WebrpcHeader = "Webrpc"

const WebrpcHeaderValue = "webrpc@v0.31.1;gen-golang@v0.23.3;quota-control@v0-26.1.5+3f8a484"

type WebrpcGenVersions struct {
	WebrpcGenVersion string
	CodeGenName      string
	CodeGenVersion   string
	SchemaName       string
	SchemaVersion    string
}

func VersionFromHeader(h http.Header) (*WebrpcGenVersions, error) {
	if h.Get(WebrpcHeader) == "" {
		return nil, fmt.Errorf("header is empty or missing")
	}

	versions, err := parseWebrpcGenVersions(h.Get(WebrpcHeader))
	if err != nil {
		return nil, fmt.Errorf("webrpc header is invalid: %w", err)
	}

	return versions, nil
}

func parseWebrpcGenVersions(header string) (*WebrpcGenVersions, error) {
	versions := strings.Split(header, ";")
	if len(versions) < 3 {
		return nil, fmt.Errorf("expected at least 3 parts while parsing webrpc header: %v", header)
	}

	_, webrpcGenVersion, ok := strings.Cut(versions[0], "@")
	if !ok {
		return nil, fmt.Errorf("webrpc gen version could not be parsed from: %s", versions[0])
	}

	tmplTarget, tmplVersion, ok := strings.Cut(versions[1], "@")
	if !ok {
		return nil, fmt.Errorf("tmplTarget and tmplVersion could not be parsed from: %s", versions[1])
	}

	schemaName, schemaVersion, ok := strings.Cut(versions[2], "@")
	if !ok {
		return nil, fmt.Errorf("schema name and schema version could not be parsed from: %s", versions[2])
	}

	return &WebrpcGenVersions{
		WebrpcGenVersion: webrpcGenVersion,
		CodeGenName:      tmplTarget,
		CodeGenVersion:   tmplVersion,
		SchemaName:       schemaName,
		SchemaVersion:    schemaVersion,
	}, nil
}
