name: Retro compatibility tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  retro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Start Redis
      uses: supercharge/redis-github-action@1.8.1

    - name: Run server
      run: cd tests && make server-start

    - name: Run latest client tests
      run: cd tests && make client-run-latest

    - name: Run v0.23 client tests
      run: cd tests && make client-run-v0.23

    - name: Stop server
      run: cd tests && make server-stop
      if: always()
